/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Neural Inverse Corporation. All rights reserved.
 *  Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * Linker Script Generator
 *
 * Generates complete .ld linker scripts from MCU memory maps.
 * Not a template engine — computes region layout from the actual
 * hardware specs in the firmware session.
 */

import { IFirmwareSessionService } from '../../firmwareSessionService.js';
import { ILinkerScriptConfig, IMemoryRegionConfig } from './memoryTypes.js';

export class LinkerScriptGenerator {

	constructor(private readonly _session: IFirmwareSessionService) {}

	generate(config?: Partial<ILinkerScriptConfig>): string {
		const s = this._session.session;
		if (!s.isActive || !s.mcuConfig) { return '/* No active firmware session */'; }

		const mcu = s.mcuConfig;
		const family = mcu.family?.toUpperCase() ?? '';

		const fullConfig = this._buildConfig(config, mcu, family);
		const lines: string[] = [];

		// Header
		lines.push('/*');
		lines.push(` * Linker script for ${mcu.family} ${mcu.variant}`);
		lines.push(` * Generated by Neural Inverse from MCU database`);
		lines.push(` * Flash: ${(fullConfig.flashSize / 1024).toFixed(0)} KB @ 0x${fullConfig.flashOrigin.toString(16).toUpperCase()}`);
		lines.push(` * RAM:   ${(fullConfig.ramSize / 1024).toFixed(0)} KB @ 0x${fullConfig.ramOrigin.toString(16).toUpperCase()}`);
		if (fullConfig.rtos && fullConfig.rtos !== 'none') {
			lines.push(` * RTOS:  ${fullConfig.rtos} (heap: ${(fullConfig.rtosHeapSize ?? fullConfig.heapSize) / 1024} KB)`);
		}
		lines.push(' */');
		lines.push('');

		// Entry point
		lines.push('ENTRY(Reset_Handler)');
		lines.push('');

		// Stack/heap symbols
		lines.push(`_Min_Heap_Size = 0x${fullConfig.heapSize.toString(16)};`);
		lines.push(`_Min_Stack_Size = 0x${fullConfig.stackSize.toString(16)};`);
		lines.push('');

		// Memory regions
		lines.push('MEMORY');
		lines.push('{');
		lines.push(`  FLASH (rx)  : ORIGIN = 0x${fullConfig.flashOrigin.toString(16).toUpperCase()}, LENGTH = ${fullConfig.flashSize / 1024}K`);
		lines.push(`  RAM (xrw)   : ORIGIN = 0x${fullConfig.ramOrigin.toString(16).toUpperCase()}, LENGTH = ${fullConfig.ramSize / 1024}K`);

		for (const region of fullConfig.additionalRegions) {
			const attrs = region.attributes;
			const sizeK = region.size >= 1024 ? `${region.size / 1024}K` : `${region.size}`;
			lines.push(`  ${region.name.padEnd(10)} (${attrs.padEnd(4)}) : ORIGIN = 0x${region.origin.toString(16).toUpperCase()}, LENGTH = ${sizeK}`);
		}

		lines.push('}');
		lines.push('');

		// Sections
		lines.push('SECTIONS');
		lines.push('{');

		// RP2040: .boot2 must be first section at flash base
		if (family.startsWith('RP20') || family.startsWith('NRF52') || family.startsWith('NRF53')) {
			if (family.startsWith('RP20')) {
				lines.push('  .boot2 :');
				lines.push('  {');
				lines.push('    . = ALIGN(256);');
				lines.push('    KEEP(*(.boot2))');
				lines.push('    . = ALIGN(256);');
				lines.push('  } >BOOT2');
				lines.push('');
			}
		}

		// .isr_vector
		lines.push('  .isr_vector :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    KEEP(*(.isr_vector))');
		lines.push('    . = ALIGN(4);');
		lines.push('  } >FLASH');
		lines.push('');

		// .text
		lines.push('  .text :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    *(.text)');
		lines.push('    *(.text*)');
		lines.push('    *(.glue_7)');
		lines.push('    *(.glue_7t)');
		lines.push('    *(.eh_frame)');
		lines.push('    KEEP(*(.init))');
		lines.push('    KEEP(*(.fini))');
		lines.push('    . = ALIGN(4);');
		lines.push('    _etext = .;');
		lines.push('  } >FLASH');
		lines.push('');

		// .rodata
		lines.push('  .rodata :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    *(.rodata)');
		lines.push('    *(.rodata*)');
		lines.push('    . = ALIGN(4);');
		lines.push('  } >FLASH');
		lines.push('');

		// ARM extab/exidx
		lines.push('  .ARM.extab : { *(.ARM.extab* .gnu.linkonce.armextab.*) } >FLASH');
		lines.push('  .ARM : {');
		lines.push('    __exidx_start = .;');
		lines.push('    *(.ARM.exidx*)');
		lines.push('    __exidx_end = .;');
		lines.push('  } >FLASH');
		lines.push('');

		// .preinit_array, .init_array, .fini_array
		lines.push('  .preinit_array :');
		lines.push('  {');
		lines.push('    PROVIDE_HIDDEN(__preinit_array_start = .);');
		lines.push('    KEEP(*(.preinit_array*))');
		lines.push('    PROVIDE_HIDDEN(__preinit_array_end = .);');
		lines.push('  } >FLASH');
		lines.push('');
		lines.push('  .init_array :');
		lines.push('  {');
		lines.push('    PROVIDE_HIDDEN(__init_array_start = .);');
		lines.push('    KEEP(*(SORT(.init_array.*)))');
		lines.push('    KEEP(*(.init_array*))');
		lines.push('    PROVIDE_HIDDEN(__init_array_end = .);');
		lines.push('  } >FLASH');
		lines.push('');
		lines.push('  .fini_array :');
		lines.push('  {');
		lines.push('    PROVIDE_HIDDEN(__fini_array_start = .);');
		lines.push('    KEEP(*(SORT(.fini_array.*)))');
		lines.push('    KEEP(*(.fini_array*))');
		lines.push('    PROVIDE_HIDDEN(__fini_array_end = .);');
		lines.push('  } >FLASH');
		lines.push('');

		// _sidata for .data initialization
		lines.push('  _sidata = LOADADDR(.data);');
		lines.push('');

		// .data (initialized data in RAM, loaded from FLASH)
		lines.push('  .data :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    _sdata = .;');
		lines.push('    *(.data)');
		lines.push('    *(.data*)');
		lines.push('    . = ALIGN(4);');
		lines.push('    _edata = .;');
		lines.push('  } >RAM AT> FLASH');
		lines.push('');

		// .bss
		lines.push('  .bss :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    _sbss = .;');
		lines.push('    __bss_start__ = _sbss;');
		lines.push('    *(.bss)');
		lines.push('    *(.bss*)');
		lines.push('    *(COMMON)');
		lines.push('    . = ALIGN(4);');
		lines.push('    _ebss = .;');
		lines.push('    __bss_end__ = _ebss;');
		lines.push('  } >RAM');
		lines.push('');

		// Heap and stack
		lines.push('  ._user_heap_stack :');
		lines.push('  {');
		lines.push('    . = ALIGN(8);');
		lines.push('    PROVIDE(end = .);');
		lines.push('    PROVIDE(_end = .);');
		lines.push('    . = . + _Min_Heap_Size;');
		lines.push('    . = . + _Min_Stack_Size;');
		lines.push('    . = ALIGN(8);');
		lines.push('  } >RAM');
		lines.push('');

		// .ramfunc: functions that must execute from RAM (e.g. flash erase/write routines)
		lines.push('  .ramfunc :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    _sramfunc = .;');
		lines.push('    *(.ramfunc)');
		lines.push('    *(.ramfunc.*)');
		lines.push('    . = ALIGN(4);');
		lines.push('    _eramfunc = .;');
		lines.push('  } >RAM AT> FLASH');
		lines.push('');

		// .noinit: variables that must NOT be zeroed at startup (e.g. boot flags, watchdog counters)
		lines.push('  .noinit (NOLOAD) :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    *(.noinit)');
		lines.push('    *(.noinit.*)');
		lines.push('    . = ALIGN(4);');
		lines.push('  } >RAM');
		lines.push('');

		// CCM/DTCM sections if applicable
		for (const region of fullConfig.additionalRegions) {
			const sectionName = region.name.toLowerCase();
			lines.push(`  /* ${region.name}: ${region.description ?? ''} */`);
			if (!region.isDMAAccessible) {
				lines.push(`  /* WARNING: ${region.name} is NOT DMA-accessible. Never place DMA buffers here. */`);
			}
			lines.push(`  .${sectionName} (NOLOAD) :`);
			lines.push('  {');
			lines.push('    . = ALIGN(4);');
			lines.push(`    *(.${sectionName})`);
			lines.push(`    *(.${sectionName}.*)`);
			lines.push('    . = ALIGN(4);');
			lines.push(`  } >${region.name}`);
			lines.push('');
		}

		lines.push('  /DISCARD/ :');
		lines.push('  {');
		lines.push('    libc.a(*)');
		lines.push('    libm.a(*)');
		lines.push('    libgcc.a(*)');
		lines.push('  }');
		lines.push('');

		// Stack pointer init — Harvard architectures (AVR, C2000) have different stack placement
		const fam = family.toUpperCase();
		if (fam.startsWith('ATMEGA') || fam.startsWith('ATTINY') || fam.startsWith('AVR')) {
			lines.push(`  /* AVR: stack grows down from SRAM end. RAMEND is defined in device headers. */`);
			lines.push(`  _estack = ORIGIN(RAM) + LENGTH(RAM) - 1;  /* AVR SP = RAMEND at reset */`);
		} else if (fam.startsWith('TMS320') || fam.startsWith('C2000')) {
			lines.push(`  /* C2000: stack in SARAM (data space), not at flash end */`);
			lines.push(`  _estack = ORIGIN(RAM) + LENGTH(RAM);  /* SARAM end */`);
		} else {
			lines.push(`  _estack = ORIGIN(RAM) + LENGTH(RAM);`);
		}

		lines.push('}');

		return lines.join('\n');
	}

	private _buildConfig(
		override: Partial<ILinkerScriptConfig> | undefined,
		mcu: { flashSize: number; ramSize: number; memoryMap?: Array<{ name: string; baseAddress: number; size: number }> },
		family: string,
	): ILinkerScriptConfig {
		const fam = family.toUpperCase();
		const defaults = this._getMemoryOrigins(fam, mcu.memoryMap);
		const flashOrigin = override?.flashOrigin ?? defaults.flashOrigin;
		const flashSize = override?.flashSize ?? mcu.flashSize;
		const ramOrigin = override?.ramOrigin ?? defaults.ramOrigin;
		const ramSize = override?.ramSize ?? mcu.ramSize;

		const additionalRegions: IMemoryRegionConfig[] = override?.additionalRegions ?? [];

		// Detect special memory regions from MCU memory map or family
		if (additionalRegions.length === 0) {
			// STM32F4 CCM RAM: only on devices with >= 192 KB RAM (F405/F407/F415/F417/F427/F429/F437/F439/F446/F469/F479)
			if (family.startsWith('STM32F4') && ramSize >= 192 * 1024) {
				additionalRegions.push({
					name: 'CCMRAM',
					origin: 0x10000000,
					size: 64 * 1024,
					attributes: 'rw',
					isDMAAccessible: false,
					description: 'Core-Coupled Memory — 64 KB, CPU-only (no DMA). Use for: stack, algorithm buffers, critical data.',
				});
			}
			// STM32F7 DTCM
			if (family.startsWith('STM32F7')) {
				additionalRegions.push({
					name: 'DTCM',
					origin: 0x20000000,
					size: 64 * 1024,
					attributes: 'rw',
					isDMAAccessible: false,
					description: 'Data TCM — 64 KB, zero-wait-state access, no DMA. Use for: ISR data, FreeRTOS heap, stack.',
				});
				additionalRegions.push({
					name: 'ITCM',
					origin: 0x00000000,
					size: 16 * 1024,
					attributes: 'rwx',
					isDMAAccessible: false,
					description: 'Instruction TCM — 16 KB, zero-wait-state, no DMA. Use for: latency-critical ISRs, DSP routines.',
				});
			}
			// STM32H7 DTCM + ITCM + AXI SRAM
			if (family.startsWith('STM32H7')) {
				additionalRegions.push({
					name: 'DTCM',
					origin: 0x20000000,
					size: 128 * 1024,
					attributes: 'rw',
					isDMAAccessible: false,
					description: 'Data TCM — 128 KB, CPU-only, no DMA. Ideal for: ISR stack, FreeRTOS heap.',
				});
				additionalRegions.push({
					name: 'ITCM',
					origin: 0x00000000,
					size: 64 * 1024,
					attributes: 'rwx',
					isDMAAccessible: false,
					description: 'Instruction TCM — 64 KB, CPU-only. Use __attribute__((section(".itcm"))) for critical ISRs.',
				});
				additionalRegions.push({
					name: 'AXI_SRAM',
					origin: 0x24000000,
					size: 512 * 1024,
					attributes: 'xrw',
					isDMAAccessible: true,
					description: 'AXI SRAM — 512 KB, DMA-accessible. Use for DMA buffers, framebuffers, Ethernet descriptors.',
				});
			}
			// STM32F4/F7/H7 Backup SRAM
			if (family.startsWith('STM32F4') || family.startsWith('STM32F7') || family.startsWith('STM32H7')) {
				additionalRegions.push({
					name: 'BKPSRAM',
					origin: 0x40024000,
					size: 4 * 1024,
					attributes: 'rw',
					isDMAAccessible: false,
					description: 'Backup SRAM — 4 KB, retained on VBAT. Requires RCC->AHB1ENR BKPSRAMEN + PWR->CR DBP. Use for: crash logs, boot counters.',
				});
			}
			// nRF52/53: UICR (user config) and FICR (factory config) are at fixed addresses
			if (family.startsWith('NRF52') || family.startsWith('NRF53') || family.startsWith('NRF91')) {
				additionalRegions.push({
					name: 'FICR',
					origin: 0x10000000,
					size: 4 * 1024,
					attributes: 'r',
					isDMAAccessible: false,
					description: 'Factory Information Configuration Registers (read-only, programmed at factory)',
				});
				additionalRegions.push({
					name: 'UICR',
					origin: 0x10001000,
					size: 4 * 1024,
					attributes: 'rw',
					isDMAAccessible: false,
					description: 'User Information Configuration Registers (bootloader config, APPROTECT, REGOUT)',
				});
			}
			// RP2040/RP2350: needs .boot2 section (256-byte second-stage bootloader at flash start)
			if (family.startsWith('RP20')) {
				additionalRegions.push({
					name: 'BOOT2',
					origin: 0x10000000,
					size: 256,
					attributes: 'rx',
					isDMAAccessible: false,
					description: 'Second-stage bootloader (256 bytes at XIP flash base, required by RP2040 boot ROM)',
				});
				additionalRegions.push({
					name: 'XIP_SRAM',
					origin: 0x15000000,
					size: 16 * 1024,
					attributes: 'xrw',
					isDMAAccessible: true,
					description: 'XIP SRAM — 16 KB, usable for time-critical code after copying from flash',
				});
			}
			// From MCU memory map if available
			if (mcu.memoryMap) {
				for (const region of mcu.memoryMap) {
					const nameUpper = region.name.toUpperCase();
					if (nameUpper === 'FLASH' || nameUpper === 'RAM' || nameUpper === 'SRAM') { continue; }
					if (additionalRegions.some(r => r.origin === region.baseAddress)) { continue; }
					additionalRegions.push({
						name: region.name,
						origin: region.baseAddress,
						size: region.size,
						attributes: nameUpper.includes('FLASH') || nameUpper.includes('ROM') ? 'rx' : 'rw',
						isDMAAccessible: !nameUpper.includes('TCM') && !nameUpper.includes('CCM'),
						description: `From MCU memory map`,
					});
				}
			}
		}

		const rtosRaw = override?.rtos ?? (this._session.session.rtos as unknown as string) ?? 'none';
		const rtos: 'freertos' | 'zephyr' | 'none' = (rtosRaw === 'freertos' || rtosRaw === 'zephyr') ? rtosRaw : 'none';
		const stackSize = override?.stackSize ?? (rtos === 'freertos' ? 0x800 : 0x400);
		const heapSize = override?.heapSize ?? (rtos === 'freertos' ? 0x4000 : 0x200);

		return {
			flashOrigin,
			flashSize,
			ramOrigin,
			ramSize,
			additionalRegions,
			stackSize,
			heapSize,
			minStackSize: override?.minStackSize ?? 0x200,
			rtos,
			rtosHeapSize: override?.rtosHeapSize ?? (rtos === 'freertos' ? heapSize : undefined),
			dmaBufferRegion: override?.dmaBufferRegion ?? 'RAM',
		};
	}

	private _getMemoryOrigins(
		fam: string,
		memoryMap?: Array<{ name: string; baseAddress: number; size: number }>,
	): { flashOrigin: number; ramOrigin: number } {
		// If the session MCU database has a memory map, prefer it
		if (memoryMap) {
			const flash = memoryMap.find(r => r.name.toUpperCase().includes('FLASH') || r.name.toUpperCase() === 'ROM');
			const ram = memoryMap.find(r => r.name.toUpperCase() === 'SRAM' || r.name.toUpperCase() === 'RAM');
			if (flash && ram) { return { flashOrigin: flash.baseAddress, ramOrigin: ram.baseAddress }; }
		}

		// ── STM32 ──────────────────────────────────────────────────────────
		if (fam.startsWith('STM32')) { return { flashOrigin: 0x08000000, ramOrigin: 0x20000000 }; }

		// ── Nordic nRF52/53/91 ────────────────────────────────────────────
		if (fam.startsWith('NRF52') || fam.startsWith('NRF51')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}
		if (fam.startsWith('NRF53')) {
			// nRF5340 App core
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}
		if (fam.startsWith('NRF91')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}
		if (fam.startsWith('NRF')) { return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 }; }

		// ── RP2040 / RP2350 ───────────────────────────────────────────────
		if (fam.startsWith('RP20')) {
			// RP2040: XIP flash at 0x10000000, SRAM at 0x20000000
			return { flashOrigin: 0x10000000, ramOrigin: 0x20000000 };
		}

		// ── ESP32 (raw GCC toolchain — IDF manages its own LD) ─────────────
		if (fam.startsWith('ESP32') || fam.startsWith('ESP8266')) {
			// IRAM: 0x40080000, DRAM: 0x3FFC0000, Flash mapped via DROM
			return { flashOrigin: 0x400D0000, ramOrigin: 0x3FFC0000 };
		}

		// ── NXP Kinetis K/L/V ─────────────────────────────────────────────
		if (fam.startsWith('MK') || fam.startsWith('KINETIS')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x1FFF0000 };
		}

		// ── NXP i.MX RT ───────────────────────────────────────────────────
		if (fam.startsWith('MIMXRT')) {
			// FlexSPI (QSPI flash) at 0x60000000, OCRAM at 0x20200000
			return { flashOrigin: 0x60000000, ramOrigin: 0x20200000 };
		}

		// ── NXP LPC ───────────────────────────────────────────────────────
		if (fam.startsWith('LPC')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}

		// ── Microchip SAM D/E/C/L ─────────────────────────────────────────
		if (fam.startsWith('SAM') || fam.startsWith('ATSAM')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}

		// ── Microchip AVR (ATmega / ATtiny) ───────────────────────────────
		if (fam.startsWith('ATMEGA') || fam.startsWith('ATTINY') || fam.startsWith('AVR')) {
			// Harvard: flash at 0x00000000 (PROGMEM), SRAM at 0x00800000 (mapped)
			return { flashOrigin: 0x00000000, ramOrigin: 0x00800060 };
		}

		// ── Renesas RA ────────────────────────────────────────────────────
		if (fam.startsWith('RA') || fam.startsWith('R7FA') || fam.startsWith('R5F')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}

		// ── Renesas RX ────────────────────────────────────────────────────
		if (fam.startsWith('RX')) {
			return { flashOrigin: 0xFFE00000, ramOrigin: 0x00000000 };
		}

		// ── TI C2000 (C28x Harvard) ───────────────────────────────────────
		if (fam.startsWith('TMS320') || fam.startsWith('C2000')) {
			return { flashOrigin: 0x080000, ramOrigin: 0x000000 };
		}

		// ── AURIX TC2xx/TC3xx (TriCore) ───────────────────────────────────
		// TriCore uses segmented addressing. PFlash segment A is cached at 0xA0000000.
		// The non-cached alias is 0x80000000 (used for DMA/write). Linkers use 0xA0000000.
		// LMU (Local Memory Unit) RAM at 0x900XXXXX; CPU0 DSPR at 0x70000000.
		if (fam.startsWith('TC2') || fam.startsWith('TC3') || fam.startsWith('TC4') || fam.startsWith('AURIX')) {
			return { flashOrigin: 0xA0000000, ramOrigin: 0x70000000 };
		}

		// ── Silicon Labs EFR32 / EFM32 ────────────────────────────────────
		if (fam.startsWith('EFR32') || fam.startsWith('EFM32')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}

		// ── PSoC 4 / PSoC 6 ───────────────────────────────────────────────
		if (fam.startsWith('PSOC 6') || fam.startsWith('CY8C6')) {
			return { flashOrigin: 0x10000000, ramOrigin: 0x08000000 };
		}
		if (fam.startsWith('PSOC 4') || fam.startsWith('CY8C4')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}

		// ── TM4C / Hercules (TI Arm-M) ────────────────────────────────────
		if (fam.startsWith('TM4C') || fam.startsWith('HERCULES') || fam.startsWith('TMS570')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}

		// ── MSP430 (16-bit Harvard) ───────────────────────────────────────
		// Flash: 0xFFFF - size + 1 (top of address space), RAM: 0x0200
		if (fam.startsWith('MSP430')) {
			return { flashOrigin: 0xC000, ramOrigin: 0x0200 };
		}

		// ── MSP432 (Arm M4F) ─────────────────────────────────────────────
		if (fam.startsWith('MSP432')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}

		// ── Infineon XMC1xxx / XMC4xxx ───────────────────────────────────
		if (fam.startsWith('XMC1')) {
			return { flashOrigin: 0x10001000, ramOrigin: 0x20000000 }; // XMC1: ROM at 0x10001000
		}
		if (fam.startsWith('XMC4')) {
			return { flashOrigin: 0x0C000000, ramOrigin: 0x20000000 }; // XMC4: Flash at 0x0C000000
		}

		// ── Ambiq Apollo ─────────────────────────────────────────────────
		if (fam.startsWith('APOLLO') || fam.startsWith('AM')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x10000000 };
		}

		// ── Maxim MAX32 ───────────────────────────────────────────────────
		if (fam.startsWith('MAX32')) {
			return { flashOrigin: 0x10000000, ramOrigin: 0x20000000 };
		}

		// ── NXP S32K / S32G ───────────────────────────────────────────────
		if (fam.startsWith('S32K') || fam.startsWith('S32G')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20240000 };
		}

		// ── Nuvoton M480 / M2354 ─────────────────────────────────────────
		if (fam.startsWith('M480') || fam.startsWith('M2354') || fam.startsWith('NUVOTON') || fam.startsWith('NUC')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}

		// ── Renesas RL78 (16-bit Harvard) ────────────────────────────────
		if (fam.startsWith('RL78')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0xFFE20 }; // RL78 data RAM
		}

		// ── Renesas RX ───────────────────────────────────────────────────
		if (fam.startsWith('RX')) {
			return { flashOrigin: 0xFFE00000, ramOrigin: 0x00000000 };
		}

		// ── WCH CH32V ─────────────────────────────────────────────────────
		if (fam.startsWith('CH32')) {
			return { flashOrigin: 0x08000000, ramOrigin: 0x20000000 };
		}

		// ── Puya PY32 (STM32-compatible) ─────────────────────────────────
		if (fam.startsWith('PY32')) {
			return { flashOrigin: 0x08000000, ramOrigin: 0x20000000 };
		}

		// ── Microchip PIC32 (MIPS32) ──────────────────────────────────────
		if (fam.startsWith('PIC32')) {
			return { flashOrigin: 0x9D000000, ramOrigin: 0xA0000000 }; // MIPS virtual addresses
		}

		// ── Microchip PIC18/16/24 (8/16-bit Harvard) ─────────────────────
		if (fam.startsWith('PIC18') || fam.startsWith('PIC16') || fam.startsWith('PIC24') || fam.startsWith('DSPIC')) {
			return { flashOrigin: 0x000000, ramOrigin: 0x000000 }; // PIC uses program memory addressing
		}

		// ── SiFive / RISC-V SoC ───────────────────────────────────────────
		if (fam.startsWith('FE310') || fam.startsWith('FU740') || fam.startsWith('K210') || fam.startsWith('BL6')) {
			return { flashOrigin: 0x20000000, ramOrigin: 0x80000000 };
		}

		// ── AllWinner D1 / T-Head ─────────────────────────────────────────
		if (fam === 'D1' || fam.startsWith('ALLWINNER')) {
			return { flashOrigin: 0x40200000, ramOrigin: 0x40000000 };
		}

		// ── TI AM33xx / AM57x / AM64x (Linux SoC) ────────────────────────
		if (fam.startsWith('AM3') || fam.startsWith('AM5') || fam.startsWith('AM6')) {
			// These run Linux — not bare-metal linker scripts
			return { flashOrigin: 0x80000000, ramOrigin: 0x80000000 };
		}

		// ── GD32 (STM32-compatible) ───────────────────────────────────────
		if (fam.startsWith('GD32')) { return { flashOrigin: 0x08000000, ramOrigin: 0x20000000 }; }

		// ── NXP LPC8/17/40/43/55 + MCX ───────────────────────────────────
		if (fam.startsWith('LPC') || fam.startsWith('MCX')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}

		// ── Cypress FM4 (Arm M4) ──────────────────────────────────────────
		if (fam.startsWith('FM4') || fam.startsWith('S6E')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x1FFE0000 };
		}

		// ── SiFive FE310 / FU740 / K210 (RISC-V) ─────────────────────────
		if (fam.startsWith('FE310')) {
			return { flashOrigin: 0x20010000, ramOrigin: 0x80000000 }; // FE310: QSPI XIP, DTIM
		}
		if (fam.startsWith('FU740') || fam.startsWith('K210')) {
			return { flashOrigin: 0x20000000, ramOrigin: 0x80000000 };
		}

		// ── Arm Cortex-M55 reference design ──────────────────────────────
		if (fam.startsWith('M55') || fam.startsWith('CORSTONE')) {
			return { flashOrigin: 0x10000000, ramOrigin: 0x21000000 };
		}

		// ── BL602 / BL60x / BL61x (Bouffalo Lab) ─────────────────────────
		if (fam.startsWith('BL60') || fam.startsWith('BL61') || fam.startsWith('BL602')) {
			return { flashOrigin: 0x23000000, ramOrigin: 0x22020000 };
		}

		// ── TI CC13xx / CC23xx / CC26xx / CC32xx (SimpleLink) ─────────────
		if (fam.startsWith('CC13') || fam.startsWith('CC23') || fam.startsWith('CC26') || fam.startsWith('CC32')) {
			return { flashOrigin: 0x00000000, ramOrigin: 0x20000000 };
		}

		// ── AM335x / AM57x / AM62x / AM64x / AM243x (Linux SoC) ──────────
		// These run Linux from DDR; bare-metal startup at 0x80000000 (DDR)
		if (fam.startsWith('AM') || fam.startsWith('BCM') || fam.startsWith('SAMA7')) {
			return { flashOrigin: 0x80000000, ramOrigin: 0x80000000 };
		}

		// ── RP2350 (same as RP2040 XIP flash) ────────────────────────────
		if (fam.startsWith('RP2350')) { return { flashOrigin: 0x10000000, ramOrigin: 0x20000000 }; }

		// ── NXP i.MX RT (FlexSPI XIP flash) ─────────────────────────────
		if (fam.startsWith('I.MX') || fam.startsWith('IMXRT')) { return { flashOrigin: 0x60000000, ramOrigin: 0x20200000 }; }

		// ── Lattice FPGA / PolarFire (soft CPU) ──────────────────────────
		if (fam.startsWith('MACHXO') || fam.startsWith('POLARFIRE')) { return { flashOrigin: 0x60000000, ramOrigin: 0x80000000 }; }

		// ── Virtual (simulation) ─────────────────────────────────────────
		if (fam === 'VIRTUAL') { return { flashOrigin: 0x08000000, ramOrigin: 0x20000000 }; }

		// Default: STM32-style (also covers any remaining Cortex-M without explicit entry)
		return { flashOrigin: 0x08000000, ramOrigin: 0x20000000 };
	}
}
