/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Neural Inverse Corporation. All rights reserved.
 *  Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * Linker Script Generator
 *
 * Generates complete .ld linker scripts from MCU memory maps.
 * Not a template engine — computes region layout from the actual
 * hardware specs in the firmware session.
 */

import { IFirmwareSessionService } from '../../firmwareSessionService.js';
import { ILinkerScriptConfig, IMemoryRegionConfig } from './memoryTypes.js';

export class LinkerScriptGenerator {

	constructor(private readonly _session: IFirmwareSessionService) {}

	generate(config?: Partial<ILinkerScriptConfig>): string {
		const s = this._session.session;
		if (!s.isActive || !s.mcuConfig) { return '/* No active firmware session */'; }

		const mcu = s.mcuConfig;
		const family = mcu.family?.toUpperCase() ?? '';

		const fullConfig = this._buildConfig(config, mcu, family);
		const lines: string[] = [];

		// Header
		lines.push('/*');
		lines.push(` * Linker script for ${mcu.family} ${mcu.variant}`);
		lines.push(` * Generated by Neural Inverse from MCU database`);
		lines.push(` * Flash: ${(fullConfig.flashSize / 1024).toFixed(0)} KB @ 0x${fullConfig.flashOrigin.toString(16).toUpperCase()}`);
		lines.push(` * RAM:   ${(fullConfig.ramSize / 1024).toFixed(0)} KB @ 0x${fullConfig.ramOrigin.toString(16).toUpperCase()}`);
		if (fullConfig.rtos && fullConfig.rtos !== 'none') {
			lines.push(` * RTOS:  ${fullConfig.rtos} (heap: ${(fullConfig.rtosHeapSize ?? fullConfig.heapSize) / 1024} KB)`);
		}
		lines.push(' */');
		lines.push('');

		// Entry point
		lines.push('ENTRY(Reset_Handler)');
		lines.push('');

		// Stack/heap symbols
		lines.push(`_Min_Heap_Size = 0x${fullConfig.heapSize.toString(16)};`);
		lines.push(`_Min_Stack_Size = 0x${fullConfig.stackSize.toString(16)};`);
		lines.push('');

		// Memory regions
		lines.push('MEMORY');
		lines.push('{');
		lines.push(`  FLASH (rx)  : ORIGIN = 0x${fullConfig.flashOrigin.toString(16).toUpperCase()}, LENGTH = ${fullConfig.flashSize / 1024}K`);
		lines.push(`  RAM (xrw)   : ORIGIN = 0x${fullConfig.ramOrigin.toString(16).toUpperCase()}, LENGTH = ${fullConfig.ramSize / 1024}K`);

		for (const region of fullConfig.additionalRegions) {
			const attrs = region.attributes;
			const sizeK = region.size >= 1024 ? `${region.size / 1024}K` : `${region.size}`;
			lines.push(`  ${region.name.padEnd(10)} (${attrs.padEnd(4)}) : ORIGIN = 0x${region.origin.toString(16).toUpperCase()}, LENGTH = ${sizeK}`);
		}

		lines.push('}');
		lines.push('');

		// Sections
		lines.push('SECTIONS');
		lines.push('{');

		// .isr_vector
		lines.push('  .isr_vector :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    KEEP(*(.isr_vector))');
		lines.push('    . = ALIGN(4);');
		lines.push('  } >FLASH');
		lines.push('');

		// .text
		lines.push('  .text :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    *(.text)');
		lines.push('    *(.text*)');
		lines.push('    *(.glue_7)');
		lines.push('    *(.glue_7t)');
		lines.push('    *(.eh_frame)');
		lines.push('    KEEP(*(.init))');
		lines.push('    KEEP(*(.fini))');
		lines.push('    . = ALIGN(4);');
		lines.push('    _etext = .;');
		lines.push('  } >FLASH');
		lines.push('');

		// .rodata
		lines.push('  .rodata :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    *(.rodata)');
		lines.push('    *(.rodata*)');
		lines.push('    . = ALIGN(4);');
		lines.push('  } >FLASH');
		lines.push('');

		// ARM extab/exidx
		lines.push('  .ARM.extab : { *(.ARM.extab* .gnu.linkonce.armextab.*) } >FLASH');
		lines.push('  .ARM : {');
		lines.push('    __exidx_start = .;');
		lines.push('    *(.ARM.exidx*)');
		lines.push('    __exidx_end = .;');
		lines.push('  } >FLASH');
		lines.push('');

		// .preinit_array, .init_array, .fini_array
		lines.push('  .preinit_array :');
		lines.push('  {');
		lines.push('    PROVIDE_HIDDEN(__preinit_array_start = .);');
		lines.push('    KEEP(*(.preinit_array*))');
		lines.push('    PROVIDE_HIDDEN(__preinit_array_end = .);');
		lines.push('  } >FLASH');
		lines.push('');
		lines.push('  .init_array :');
		lines.push('  {');
		lines.push('    PROVIDE_HIDDEN(__init_array_start = .);');
		lines.push('    KEEP(*(SORT(.init_array.*)))');
		lines.push('    KEEP(*(.init_array*))');
		lines.push('    PROVIDE_HIDDEN(__init_array_end = .);');
		lines.push('  } >FLASH');
		lines.push('');
		lines.push('  .fini_array :');
		lines.push('  {');
		lines.push('    PROVIDE_HIDDEN(__fini_array_start = .);');
		lines.push('    KEEP(*(SORT(.fini_array.*)))');
		lines.push('    KEEP(*(.fini_array*))');
		lines.push('    PROVIDE_HIDDEN(__fini_array_end = .);');
		lines.push('  } >FLASH');
		lines.push('');

		// _sidata for .data initialization
		lines.push('  _sidata = LOADADDR(.data);');
		lines.push('');

		// .data (initialized data in RAM, loaded from FLASH)
		lines.push('  .data :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    _sdata = .;');
		lines.push('    *(.data)');
		lines.push('    *(.data*)');
		lines.push('    . = ALIGN(4);');
		lines.push('    _edata = .;');
		lines.push('  } >RAM AT> FLASH');
		lines.push('');

		// .bss
		lines.push('  .bss :');
		lines.push('  {');
		lines.push('    . = ALIGN(4);');
		lines.push('    _sbss = .;');
		lines.push('    __bss_start__ = _sbss;');
		lines.push('    *(.bss)');
		lines.push('    *(.bss*)');
		lines.push('    *(COMMON)');
		lines.push('    . = ALIGN(4);');
		lines.push('    _ebss = .;');
		lines.push('    __bss_end__ = _ebss;');
		lines.push('  } >RAM');
		lines.push('');

		// Heap and stack
		lines.push('  ._user_heap_stack :');
		lines.push('  {');
		lines.push('    . = ALIGN(8);');
		lines.push('    PROVIDE(end = .);');
		lines.push('    PROVIDE(_end = .);');
		lines.push('    . = . + _Min_Heap_Size;');
		lines.push('    . = . + _Min_Stack_Size;');
		lines.push('    . = ALIGN(8);');
		lines.push('  } >RAM');
		lines.push('');

		// CCM/DTCM sections if applicable
		const ccm = fullConfig.additionalRegions.find(r => r.name === 'CCMRAM' || r.name === 'DTCM');
		if (ccm) {
			lines.push(`  /* ${ccm.name}: ${ccm.description} */`);
			if (!ccm.isDMAAccessible) {
				lines.push(`  /* WARNING: ${ccm.name} is NOT DMA-accessible. Do NOT place DMA buffers here. */`);
			}
			lines.push(`  .${ccm.name.toLowerCase()} (NOLOAD) :`);
			lines.push('  {');
			lines.push('    . = ALIGN(4);');
			lines.push(`    *(.${ccm.name.toLowerCase()})`);
			lines.push(`    *(.${ccm.name.toLowerCase()}*)`);
			lines.push('    . = ALIGN(4);');
			lines.push(`  } >${ccm.name}`);
			lines.push('');
		}

		lines.push('  /DISCARD/ :');
		lines.push('  {');
		lines.push('    libc.a(*)');
		lines.push('    libm.a(*)');
		lines.push('    libgcc.a(*)');
		lines.push('  }');
		lines.push('');

		// Stack pointer init
		lines.push(`  _estack = ORIGIN(RAM) + LENGTH(RAM);`);

		lines.push('}');

		return lines.join('\n');
	}

	private _buildConfig(
		override: Partial<ILinkerScriptConfig> | undefined,
		mcu: { flashSize: number; ramSize: number; memoryMap?: Array<{ name: string; baseAddress: number; size: number }> },
		family: string,
	): ILinkerScriptConfig {
		const flashOrigin = override?.flashOrigin ?? 0x08000000;
		const flashSize = override?.flashSize ?? mcu.flashSize;
		const ramOrigin = override?.ramOrigin ?? 0x20000000;
		const ramSize = override?.ramSize ?? mcu.ramSize;

		const additionalRegions: IMemoryRegionConfig[] = override?.additionalRegions ?? [];

		// Detect CCM RAM from MCU memory map or family
		if (additionalRegions.length === 0) {
			if (family.startsWith('STM32F4') && ramSize > 128 * 1024) {
				additionalRegions.push({
					name: 'CCMRAM',
					origin: 0x10000000,
					size: 64 * 1024,
					attributes: 'rw',
					isDMAAccessible: false,
					description: 'Core-Coupled Memory (64KB, CPU-only, no DMA)',
				});
			}
			if (family.startsWith('STM32F7') || family.startsWith('STM32H7')) {
				additionalRegions.push({
					name: 'DTCM',
					origin: 0x20000000,
					size: 128 * 1024,
					attributes: 'rw',
					isDMAAccessible: false,
					description: 'Data Tightly-Coupled Memory (CPU-only, no DMA)',
				});
			}
		}

		const rtos = override?.rtos ?? (this._session.session.rtos as any) ?? 'none';
		const stackSize = override?.stackSize ?? (rtos === 'freertos' ? 0x800 : 0x400);
		const heapSize = override?.heapSize ?? (rtos === 'freertos' ? 0x4000 : 0x200);

		return {
			flashOrigin,
			flashSize,
			ramOrigin,
			ramSize,
			additionalRegions,
			stackSize,
			heapSize,
			minStackSize: override?.minStackSize ?? 0x200,
			rtos,
			rtosHeapSize: override?.rtosHeapSize ?? (rtos === 'freertos' ? heapSize : undefined),
			dmaBufferRegion: override?.dmaBufferRegion ?? 'RAM',
		};
	}
}
